### ISSUE TITLE
Protobuf.skip unimplemented types

### ISSUE THREAD

**Issue by demiurg** [SpatialServer/Leaflet.MapboxVectorTile#15]
I'm interested in rendering MVT from TileStache Vector provider:
http://tilestache.org/doc/TileStache.Goodies.VecTiles.mvt.html

However, I'm getting the Error('Unimplemented type: ' + type) for type 3, 4, 6, 7 

Should I assume these are same types as those listed here, double, int64, etc?
https://github.com/mapbox/vector-tile-spec/blob/master/1.0.1/vector_tile.proto

I'm not sure about that, because the JS source code has:
Protobuf.Int32 = 5;
but the mvt spec:
optional uint64 uint_value = 5;

So, these must be different?

What seems to be the problem, do you have any suggestions on what I should do?

**Comment by apollolm** [comment]
Hello - I'm wondering about the compression you're using with your tiles?  I've seen similar errors before, and it usually meant that our server had not compressed the .pbf file correctly.  

I've also seen this problem when I pass bogus .pbfs into the decode library: https://github.com/mapbox/vector-tile-js/issues/5

Also check this out: https://github.com/mapbox/vector-tile-js/issues/15

...And this: https://github.com/mapbox/vector-tile-js/issues/3

...or this: https://github.com/mapbox/vector-tile-spec/issues/27

A few months back, Mapbox Studio (TileMill 2) switched from using deflate to using gzip.
Older versions of TileMill2 used deflate, whereas Mapbox studio uses gzip.

Map box created a server side library to help identify which type of compression is being used. (Can't find it right now).

Do you have an example file you can attach?

**Comment by demiurg** [comment]
It looks like TileStache is using zlib to compress: 
https://github.com/TileStache/TileStache/blob/master/TileStache/Goodies/VecTiles/mvt.py

I'll check out these links, thanks!

Here is an example tile:  http://yellow.ags.io/192.mvt

**Comment by springmeyer** [comment]
last time I checked the tiles produced by TileStache are a completely difference format as the work predates the Mapbox Vector Tile Spec. So don't use or expect TileStache to work unless you add a backend to produce tiles in the Mapbox spec.

**Comment by demiurg** [comment]
Thanks, that resolves a lot of confusion for me :)

**Comment by hallahan** [comment]
Give PGRestAPI a try. This is what we use to pump out vector tiles.

https://github.com/spatialdev/PGRestAPI

**Comment by relet** [comment]
@springmeyer There also seems to be [a version over at mapzen](https://github.com/mapzen/TileStache/blob/integration-1/TileStache/Goodies/VecTiles/mapbox.py) that has a mapbox vector tile backend.

**Comment by demiurg** [comment]
I've been using the Migurskis .mvt format, since I understood what it is, it fit my needs to dynamically style and output multiple formats from same cached file.

Looking at the mapzen version: "import mapbox_vector_tile", seems like this key file is not in the repo?

**Comment by relet** [comment]
@demiurg That's a dependency to https://github.com/mapzen/mapbox-vector-tile
