### ISSUE TITLE
Uncaught Error: Unimplemented type: 4,6,7 error

### ISSUE THREAD

**Issue by Alphatiger** [SpatialServer/Leaflet.MapboxVectorTile#29]
I am trying to achieve this

Pre render all mapbox vector files (.pbf) files using tilemaker https://github.com/systemed/tilemaker  from planet OSM downloaded data and then serving them through apache server.

When i tried to use leaflet i see the error Unimplemented type: 4, Unimplemented type: 6 errors.

Any ideas, and also is there any GUI tool where i can open and check the PBF files.

**Comment by apollolm** [comment]
How are you serving the .pbf tiles?  This problem can happen if the server you're using isn't properly gzipping the files before sending them from the server to the browser.  

If you want to reference the tiles NOT using a server, but instead from a folder on your workstation (for example), you can unzip them as described [here](http://trevorpowell.com/2015/02/20/mapbox-gl-js-with-offline-vector-tiles-on-cordova/).

Here are some related links:
https://github.com/mapbox/vector-tile-js/issues/3
https://github.com/SpatialServer/Leaflet.MapboxVectorTile/issues/15

**Comment by Alphatiger** [comment]
I am using apache server and gzip is not enabled, tilemaker simply breaks the osm files into vector files (pbf) and these are served in apache  like z/x/y format , just like raster .png tiles.
I am sure the gzip is not enabled as i have tested for gzip compression.

if you are interested i can send few tiles for testing purpose which are produced from tilemaker

**Comment by apollolm** [comment]
Yes, please send over some sample files.

**Comment by Alphatiger** [comment]
Please download them from
https://www.dropbox.com/sh/s8k9lnckzoohts1/AACyUcow7v38CwdyjMTilL77a?dl=0

**Comment by apollolm** [comment]
Thanks - what is the full z/x/y address of these tiles?

**Comment by Alphatiger** [comment]
Please see below link its for rhode island, OSM file from http://download.geofabrik.de/, converted using tilemaker and hosted at ubuntu apache
http://ec2-52-3-189-41.compute-1.amazonaws.com/rhode/

**Comment by Alphatiger** [comment]
@apollolm 

Hi
Are you able to access the tiles, just want to confirm.

Regards

**Comment by apollolm** [comment]
Yes - sorry, just slammed today!

**Comment by Alphatiger** [comment]
No problem :)

**Comment by Alphatiger** [comment]
Hosted at new address http://ec2-52-3-48-243.compute-1.amazonaws.com/rhode/

**Comment by Alphatiger** [comment]
It is a compression problem, thanks for your help

**Comment by perrygeo** [comment]
@Alphatiger Could you elaborate? What was the solution?
