### ISSUE TITLE
style sheet

### ISSUE THREAD

**Issue by Alphatiger** [SpatialServer/Leaflet.MapboxVectorTile#30]
Like mapbox is there any ready to use style sheet for leaflet

**Comment by hallahan** [comment]
There is a config object to construct MVTSource that includes a style function that styles your geometries. The styling is less complex than Mapbox, and you can follow what is in the documentation to get started:

https://github.com/SpatialServer/Leaflet.MapboxVectorTile/blob/master/docs/configuration.md

There is no `style.json` like you find in MapboxGL, but you essentially set the styling of the stroke and fill of shapes being drawn to canvas in this style function.

This example shows some interesting styling of points:

https://github.com/SpatialServer/Leaflet.MapboxVectorTile/blob/7455e28429135f2284a5085ae16c92bad007f8f1/examples/confetti.js#L66

This example shows basic styling:

https://github.com/SpatialServer/Leaflet.MapboxVectorTile/blob/7455e28429135f2284a5085ae16c92bad007f8f1/examples/basic.js#L36
