### ISSUE TITLE
Open source license doesn't grant rights to use

### ISSUE THREAD

**Issue by henryptung** [SpatialServer/Leaflet.MapboxVectorTile#32]
The node project is listed on npm (and in package.json) as under ISC license.  The ISC license template contains:
```
Copyright (c) 4-digit year, Company or Person's Name

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
```
but the LICENSE file states in its place:
```
Copyright (c) 2014, Spatial Development International
All rights reserved.

Source code can be found at:
https://github.com/SpatialServer/Leaflet.MapboxVectorTile

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software including binary distrubutions.
```

Not a lawyer here, but these do _not_ sound like the same thing.

**Comment by hallahan** [comment]
https://github.com/SpatialServer/Leaflet.MapboxVectorTile/blob/master/LICENSE

Open to other suggestions though.

**Comment by henryptung** [comment]
Sorry, I pushed the green button before writing anything.

**Comment by hallahan** [comment]
lolz, no worries

**Comment by henryptung** [comment]
Ack, but I do have a concern: the LICENSE file explicitly doesn't grant the rights that the ISC one does, making the LICENSE just copyright + non-indemnification (not sure if that's the right term).

**Comment by hallahan** [comment]
What rights do you need?

**Comment by henryptung** [comment]
I'm mostly just concerned that the licenses don't match, so at the moment technically no one can legally use this without explicit approval from the owner.  The ISC license would certainly suffice, but I'm not sure if that's what you had in mind.  (If not, probably should remove the ISC token from the package.json.)

There's also the issue that because this is a project intended to be used in the frontend, the browser is very likely to load the JS files (dist, minified or not) and not the LICENSE file.  That can probably be solve though by just adding a license.js file including an @license comment with the same contents, and including that in the browserify (and also telling uglifyjs to keep license comments, since I think it currently nixes some other licenses from dependencies as well).

**Comment by henryptung** [comment]
Sorry to harp on this issue, but I'm unfortunately somewhat time-constrained and have to make a relatively immediate decision on whether we can use this library.

**Comment by hallahan** [comment]
Ok, ISC license is OK. Can you submit a pull request? You want this added to the LICENSE file?

**Comment by henryptung** [comment]
Sure, that would be just fine, I'll make a pull request.  I can also use BSD license (any of the N-clause variants) if you'd prefer, since I think that was the original license in the git history.
