### ISSUE TITLE
Issues with onClick

### ISSUE THREAD

**Issue by svancise** [SpatialServer/Leaflet.MapboxVectorTile#43]
Hi All,

I'm having a few issues when trying to work with the onClick functionality. When clicking a feature, I am getting incorrect attribute information as well as messed up feature selections (see picture for what I mean by this. Seems to be selecting only part of the feature and then incorrect tiles as well). 

For example, I have a countries layer pulled in but when clicking the United States it returns the properties for Cuba and when clicking on Canada it returns Bahamas. In some cases, it does not return a feature at all, as if there was no feature in that tile. What makes this even stranger is that after refreshing I'll get different results when clicking on the same tiles. Clicking the US will give me Honduras and clicking Canada will give me Mexico. 

I would appreciate any insight anyone can give.

Thanks!

![us_click](https://cloud.githubusercontent.com/assets/5982096/10550424/d86e5e9a-7414-11e5-970f-43ad8d0e5b56.PNG)

Edit: I have also tried this out with other point and polygon data sets as well as the data used in the samples and am having the same issues.

**Comment by apollolm** [comment]
Hi there - this sounds like the features are lacking a unique id.  When the tiles created, it is necessary to include an attribute that contains a unique id.

Then, in the config, you specify which property it is that is unique in the 'getIdForLayerFeature' function.

For example, if your unique id is called 'gid', then the function would return feature.properties.gid

Also, the onClick functionality itself isn't complete and needs work - there are two branches dealing with it - one from HenryPTung and the other from me.  

You may want to experiment with either of those branches if you're having other issues with the main branch.

Ryan

**Comment by svancise** [comment]
Hi Ryan,

Thanks for the help. Setting the feature id seems to have fixed the issue. I'll take a look at the other branches and see how it goes.

Thanks again!
