### ISSUE TITLE
leaflet 1.0.0 compatibility?

### ISSUE THREAD

**Issue by jgravois** [SpatialServer/Leaflet.MapboxVectorTile#45]
do y'all have plans to refactor this plugin to extend [`GridLayer`](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#tilelayer-api-improvements) (instead of `TileLayer.Canvas`) for compatibility w/ Leaflet `1.x`?

**Comment by wilg** [comment]
This would be great for Retina support as well!

**Comment by aalbericio** [comment]
Hello,

I'm testing this plugin against Leaflet latest version 1.0.0-beta2 and I can't make it work. Is there any plan of making it compatible with this and future versions?

Thank you in advance.

**Comment by jgravois** [comment]
we ended up using [mapbox-gl-leaflet](https://github.com/mapbox/mapbox-gl-leaflet/pull/34).

**Comment by rishabhjain30** [comment]
any updates on this? would love to take this up.

**Comment by eczajk1** [comment]
+1

**Comment by johnclittle** [comment]
+1

**Comment by dbauszus** [comment]
+1

**Comment by abenrob** [comment]
@rishabhjain30 - If you have the bandwidth/motivation, PRs would be appreciated! As of right now, there is no-one with the availability to do this, and client requirements have not required a move to 1.x. Def a good plan though.

**Comment by kentr** [comment]
I started work on this.  No ETA yet.

**Comment by hallahan** [comment]
Unfortunately, 1.0 still has not been released. We were considering supporting this several years ago, but we wanted to hold off to see if there were going to be breaking changes on 1.0. 2 years later, and 1.0 still has not been released.

It's an odd situation. [Tangram](https://github.com/tangrams/tangram) does support the 1.x release candidate. I'd recommend using Tangram if you want to use a Leaflet map. Tangram supports TopoJSON, GeoJSON, and Mapbox vector tiles.

We created this library before Tangram and MapboxGL JS were released. It was the first JS library to support Mapbox vector tiles. 

The simplicity of this library and the fact that it lends well for data overlays is a strength, and I assume this is what is motivating others to bring forward development. What are your thoughts?

**Comment by perliedman** [comment]
@hallahan It's been a long wait, and from the Leaflet team I can just say we're sorry that it ended up taking way more time than we ever planned.

Having said that, Leaflet 1.0.0 was released yesterday. Our hope is that you and everyone else will find it useful, as well as not too different from the 0.7 version - for a lot of plugins the differences are minor, although I can't say for sure for a plugin as complex as this one.

**Comment by kentr** [comment]
@hallahan My motivation is simply wanting something that works in my Leaflet-based project.  I wasn't aware of Tangram, and it might do the job.

**Comment by wilg** [comment]
Tangram and Mapbox GL JS unfortunately don't work for my use case because they require WebGL. (Which I can't use because I need to be able to render the map out via PhantomJS.)

**Comment by hallahan** [comment]
@wilg - Good point!

**Comment by wilg** [comment]
There is a similar library for Leaflet 1.0 here: https://github.com/IvanSanchez/Leaflet.VectorGrid

However it doesn't currently support click events or per-region styling currently (I think). Perhaps it makes sense to join forces? I suppose I'm a little unclear if either project is going to have much development effort going forward.

**Comment by johnclittle** [comment]
Wil

I was just thinking the exact same thing

**Comment by kentr** [comment]
Here's the work I've done, in case someone wants to continue it: https://github.com/kentr/Leaflet.MapboxVectorTile/tree/kr-leaflet-1

My approach was to create a `L.TileLayer.Canvas` class and let `MVTLayer.js` & `MVSource.js` et al continue extending it.
