### ISSUE TITLE
Does it support reading a file of vector tiles?

### ISSUE THREAD

**Issue by ghost** [SpatialServer/Leaflet.MapboxVectorTile#85]
Can I use this plugin in offline mode? (e.g. I have a file of vector tiles downloaded from: https://openmaptiles.com/downloads/dataset/osm/#0.23/0/-26)

Or the URL for vector tiles has to point to online server?

**Comment by hallahan** [comment]
No. I recommend using MapboxGL, as this plugin was built to support vector tiles before MapboxGL was mature. Consider this library deprecated.

I recommend getting started with mbview for your use case.

https://github.com/mapbox/mbview
